#!/usr/bin/env bash
# Regenerate the docs read path: FEATURE-MAP.md and INDEX.md.
#
#   build-index.sh [--root <path>] [--docs-dir <name>] [--check]
#
# FEATURE-MAP.md  the "## Key files" section of every feature README, collected
#                 into one lookup table. The README is the source; this file is
#                 derived, so the two can never disagree.
# INDEX.md        every decision and bug record, grouped by feature, read from
#                 each record's YAML frontmatter, plus the task folders under
#                 ../tasks/.
#
# --check  verify instead of write: every path listed under "## Key files" must
#          exist, and every generated file must already be up to date.
#          Exits non-zero otherwise, so CI can run it.
set -euo pipefail

# Ranges like [a-z] follow locale collation, not ASCII. Force byte semantics.
export LC_ALL=C

usage() { awk 'NR>1 && /^#/ {sub(/^# ?/, ""); print; next} NR>1 {exit}' "${BASH_SOURCE[0]}"; }

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT=""; DOCS_DIR=""; CHECK=0

while [ $# -gt 0 ]; do
  case "$1" in
    --root)     ROOT="${2:?--root needs a path}"; shift 2 ;;
    --docs-dir) DOCS_DIR="${2:?--docs-dir needs a name}"; shift 2 ;;
    --check)    CHECK=1; shift ;;
    -h|--help)  usage; exit 0 ;;
    *)          echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

# Installed as <docs>/build-index.sh; inside the skill as scripts/build-index.sh.
#
# The project root is NOT simply the parent of the docs directory: --docs-dir
# may be nested (`--docs-dir sub/docs`), while tasks/ always lives at the real
# root. Walk up looking for the markers of a root, and derive DOCS_DIR as the
# path from there — otherwise the Tasks section silently reports "none" and
# --check then calls the file stale forever.
if [ -d "$SELF_DIR/templates" ] && [ -d "$SELF_DIR/features" ]; then
  if [ -z "$ROOT" ]; then
    probe="$(dirname "$SELF_DIR")"
    ROOT="$probe"
    while :; do
      if [ -e "$probe/.git" ] || [ -d "$probe/tasks" ]; then ROOT="$probe"; break; fi
      parent="$(dirname "$probe")"
      [ "$parent" = "$probe" ] && break      # hit / — keep the default
      probe="$parent"
    done
  fi
  # DOCS_DIR is SELF_DIR relative to ROOT ("docs", or "sub/docs" when nested).
  if [ -z "$DOCS_DIR" ]; then
    abs_root="$(cd "$ROOT" && pwd)"
    case "$SELF_DIR" in
      "$abs_root"/*) DOCS_DIR="${SELF_DIR#"$abs_root"/}" ;;
      *)             DOCS_DIR="$(basename "$SELF_DIR")" ;;
    esac
  fi
else
  ROOT="${ROOT:-.}"; DOCS_DIR="${DOCS_DIR:-docs}"
fi
DOCS="$ROOT/$DOCS_DIR"

# How many "../" get from $DOCS back to $ROOT — one per component of DOCS_DIR.
# The Tasks links are relative to the generated file, which lives in $DOCS.
UP=""
_rest="$DOCS_DIR"
while [ -n "$_rest" ] && [ "$_rest" != "." ]; do
  UP="../$UP"
  _next="$(dirname "$_rest")"
  [ "$_next" = "$_rest" ] && break
  _rest="$_next"
  [ "$_rest" = "." ] && break
done
[ -n "$UP" ] || UP="../"
[ -d "$DOCS/features" ] || { echo "error: no $DOCS/features — run setup-flow.sh first" >&2; exit 2; }

BANNER="<!-- GENERATED by $DOCS_DIR/build-index.sh — do not edit; edit the source and re-run. -->"

# ---------------------------------------------------------------- helpers ---

# Feature directories, sorted, names only.
features() {
  find "$DOCS/features" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; 2>/dev/null | sort
}

# key_files <feature> — emits "path<TAB>description" for each entry under the
# README's "## Key files" heading.
key_files() {
  local readme="$DOCS/features/$1/README.md"
  [ -f "$readme" ] || return 0
  awk '
    /^##[[:space:]]+Key files[[:space:]]*$/ { inside = 1; next }
    inside && /^##[[:space:]]/ { inside = 0 }
    inside && /^[[:space:]]*-[[:space:]]*`/ {
      line = $0
      s = index(line, "`"); if (!s) next
      rest = substr(line, s+1)
      e = index(rest, "`"); if (!e) next
      path = substr(rest, 1, e-1)
      desc = substr(rest, e+1)
      sub(/^[[:space:]]*(—|-|:)[[:space:]]*/, "", desc)
      print path "\t" desc
    }
  ' "$readme"
}

# frontmatter <file> <key> — value of a top-level YAML key, empty if absent.
frontmatter() {
  awk -v want="$2" '
    NR == 1 && $0 == "---" { fm = 1; next }
    fm && $0 == "---" { exit }
    fm {
      i = index($0, ":")
      if (i) {
        k = substr($0, 1, i-1); v = substr($0, i+1)
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", k)
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", v)
        if (k == want) { print v; exit }
      }
    }
  ' "$1"
}

# cell <value> — make a value safe for a markdown table cell. An unfilled
# placeholder like `<fixed | open | wontfix>` would otherwise split into three
# columns and silently wreck the table.
cell() {
  local v="$1"
  case "$v" in ""|"[]"|"~"|"null") printf '—'; return ;; esac
  printf '%s' "$v" | sed -e 's/|/\\|/g'
}

# Paths the template ships with; they mean "nobody filled this in yet", which is
# a different problem from "this file moved".
is_placeholder() { case "$1" in src/path/to/*) return 0 ;; *) return 1 ;; esac; }

# title <file> — first top-level heading, fences ignored.
title() {
  awk '
    /^[[:space:]]*```/ { fence = !fence; next }
    !fence && /^# / { sub(/^# /, ""); print; exit }
  ' "$1"
}

# ------------------------------------------------------- FEATURE-MAP.md -----

build_feature_map() {
  printf '%s\n\n' "$BANNER"
  cat <<EOF
# Feature map

Where to look first, per feature. Each row comes from the **## Key files**
section of that feature's README — edit the README, then re-run
\`$DOCS_DIR/build-index.sh\`.

EOF
  local f had_any=0
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    local rows; rows="$(key_files "$f")"
    [ -n "$rows" ] || continue
    had_any=1
    printf '## %s\n\n' "$f"
    local readme_rel="features/$f/README.md"
    printf 'Overview: [%s](./%s)\n\n' "$readme_rel" "$readme_rel"
    printf '| File | What it does |\n| --- | --- |\n'
    local unfilled=0
    printf '%s\n' "$rows" | while IFS="$(printf '\t')" read -r path desc; do
      [ -n "$path" ] || continue
      if is_placeholder "$path"; then
        printf '| _(not filled in yet)_ | %s |\n' "$(cell "$desc")"
      else
        printf '| `%s` | %s |\n' "$path" "$(cell "$desc")"
      fi
    done
    printf '\n'
    [ "$unfilled" -eq 0 ] || true
  done <<EOF
$(features)
EOF
  if [ "$had_any" -eq 0 ]; then
    printf '_No feature README has a `## Key files` section yet._\n'
  fi
}

# ------------------------------------------------------------ INDEX.md -----

records_table() {
  local kind="$1" f file t status date extra
  local printed_any=0
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    local dir="$DOCS/features/$f/$kind"
    [ -d "$dir" ] || continue
    local files; files="$(find "$dir" -maxdepth 1 -name '*.md' | sort)"
    [ -n "$files" ] || continue
    printed_any=1
    printf '### %s\n\n' "$f"
    printf '| Record | Status | %s | Tags |\n| --- | --- | --- | --- |\n' \
      "$([ "$kind" = bugs ] && echo Found || echo Date)"
    while IFS= read -r file; do
      [ -n "$file" ] || continue
      t="$(title "$file")"; [ -n "$t" ] || t="$(basename "$file" .md)"
      status="$(frontmatter "$file" status)"
      date="$(frontmatter "$file" "$([ "$kind" = bugs ] && echo found || echo date)")"
      extra="$(frontmatter "$file" tags)"
      local rel="features/$f/$kind/$(basename "$file")"
      printf '| [%s](./%s) | %s | %s | %s |\n' \
        "$(cell "$t")" "$rel" "$(cell "$status")" "$(cell "$date")" "$(cell "$extra")"
    done <<EOF
$files
EOF
    printf '\n'
  done <<EOF
$(features)
EOF
  [ "$printed_any" -eq 1 ] || printf '_None yet._\n\n'
}

build_index() {
  printf '%s\n\n' "$BANNER"
  cat <<EOF
# Record index

Every decision and bug record, by feature, plus every unit of work under
\`tasks/\`. Generated from each record's YAML frontmatter — re-run
\`$DOCS_DIR/build-index.sh\` after adding one.

Start at [ARCHITECTURE.md](./ARCHITECTURE.md) for what the project is, and
[FEATURE-MAP.md](./FEATURE-MAP.md) for which files implement it.

## Decisions

EOF
  records_table decisions
  printf '## Bugs\n\n'
  records_table bugs
  local tasks; tasks="$(find "$ROOT/tasks" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort || true)"
  printf '## Tasks\n\n'
  printf 'Units of work, newest last. Each folder holds `design.md`, `plan.md`\n'
  printf 'and `review.md` — the *how we got here*, kept out of `%s/` on purpose.\n\n' "$DOCS_DIR"
  if [ -n "$tasks" ]; then
    printf '| Task | Artifacts |\n| --- | --- |\n'
    while IFS= read -r t; do
      [ -n "$t" ] || continue
      local name enc arts; name="$(basename "$t")"; arts=""
      # A space in a task folder name is not a valid link destination; percent-
      # encode it rather than emitting a link that resolves nowhere.
      enc="$(printf '%s' "$name" | sed 's/ /%20/g')"
      for a in design plan review; do
        [ -f "$t/$a.md" ] && arts="$arts${arts:+, }[$a](${UP}tasks/$enc/$a.md)"
      done
      printf '| [%s](%stasks/%s) | %s |\n' "$name" "$UP" "$enc" "${arts:-_empty_}"
    done <<EOF
$tasks
EOF
  else
    printf '_None yet._\n'
  fi
}

# --------------------------------------------------------------- emit -------

emit() {  # emit <builder> <destination>
  local out="$DOCS/$2"
  if [ "$CHECK" -eq 1 ]; then
    local tmp; tmp="$(mktemp "${TMPDIR:-/tmp}/build-index.XXXXXX")"
    "$1" > "$tmp"
    if [ ! -f "$out" ] || ! cmp -s "$tmp" "$out"; then
      echo "stale: $DOCS_DIR/$2 is out of date — run $DOCS_DIR/build-index.sh" >&2
      rm -f "$tmp"; return 1
    fi
    rm -f "$tmp"
  else
    "$1" > "$out"
    echo "  wrote $DOCS_DIR/$2"
  fi
}

rc=0

# Every path a feature README points at must still exist. This is the staleness
# signal: prose can rot silently, a moved file cannot.
missing=0
unfilled=""
while IFS= read -r f; do
  [ -n "$f" ] || continue
  while IFS="$(printf '\t')" read -r path _; do
    [ -n "$path" ] || continue
    if is_placeholder "$path"; then
      case " $unfilled " in *" $f "*) ;; *) unfilled="$unfilled $f" ;; esac
    elif [ ! -e "$ROOT/$path" ]; then
      echo "missing: $DOCS_DIR/features/$f/README.md lists '$path', which does not exist" >&2
      missing=$((missing + 1))
    fi
  done <<EOF
$(key_files "$f")
EOF
done <<EOF
$(features)
EOF
[ "$missing" -eq 0 ] || rc=1

# Unfilled is not an error on a fresh scaffold — but --check is what CI runs, so
# there it means nobody ever came back to finish the job.
if [ -n "$unfilled" ]; then
  echo "unfilled '## Key files':$unfilled" >&2
  [ "$CHECK" -eq 1 ] && rc=1
fi

emit build_feature_map FEATURE-MAP.md || rc=1
emit build_index INDEX.md || rc=1

if [ "$CHECK" -eq 1 ]; then
  [ "$rc" -eq 0 ] && echo "docs index is up to date; all key-file paths exist"
else
  [ "$missing" -eq 0 ] || echo "($missing key-file path(s) missing — fix the README or the list)"
fi
exit $rc
